[workspace]
members = [
	"cbz-thumbnailer",
	"cbz-thumbnailer-lib",
	"katalog-proxy",
	"katalog-proxy-lib", "katalog-proxy-thumbnailer", "thumbnailer-common",
]
default-members = ["cbz-thumbnailer"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Axel Lord"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
cbz-thumbnailer-lib = { path = "cbz-thumbnailer-lib" }
clap = "4.6.4"
color-eyre = "0.6.5"
env_logger = "0.11.11"
image = "0.25.10"
log = "0.4.33"
tap = "1.0.1"
thiserror = "2.0.19"
zip = "8.6.0"
either = "1.17.0"
katalog-proxy = { version = "0.1.0", path = "katalog-proxy" }
katalog-proxy-lib = { version = "0.1.0", path = "katalog-proxy-lib" }
open = "5.4.0"
serde = "1.0.229"
sha2 = "0.11.0"
toml = "1.1.4"
walkdir = "2.5.0"
hex = "0.4.3"
thumbnailer-common = { version = "0.1.0", path = "thumbnailer-common" }

[profile.release]
strip = "debuginfo"
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"

